# Generated by Django 5.2 on 2025-06-05 15:12

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to=users.models.get_user_media_path),
        ),
    ]
