# Generated by Django 5.2 on 2025-06-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dockerhub_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link to docker hub profile'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link to github profile'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link to LinkedIn profile'),
        ),
    ]
