# Generated by Django 5.2 on 2025-06-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_dockerhub_link_customuser_github_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='additional_info',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Contact Info'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_info',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Contact Info'),
        ),
    ]
