# Generated by Django 5.2 on 2025-07-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='External avatar URL', max_length=500, null=True),
        ),
    ]
