version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chuanitosapi_web
    command: bash -c "python manage.py collectstatic --noinput && gunicorn ChuanitosAPI.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Mount the staticfiles volume
    ports:
      - "10020:8000"
    environment:
      - DOCKERIZED=True
      - SECRET_KEY=django-insecure-z(ge4xn^owv3obq9ac)4fc&r$yu24@46rv9v#-1%m2jg-%)1hf
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 192.168.0.20
      - DATABASE_URL=postgres://chuanitos_db_admin:NiM5bipQcQEeQyKTKh5a85KPKpgMbG@192.168.0.20:10010/ChuanitosDb
volumes:
  static_volume: