# Generated by Django 5.2 on 2025-06-17 17:37

from django.db import migrations, models

import ChuanitosAPI.utils


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='documentation',
            field=models.FileField(blank=True, help_text='Upload documentation or certificate for this timeline entry', null=True, upload_to=ChuanitosAPI.utils.get_user_pdf_path),
        ),
    ]
