# Generated by Django 5.2 on 2025-05-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline_entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineentry',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
