# Generated by Django 5.2 on 2025-06-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline_entries', '0002_timelineentry_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
